axelera-model-format: 1.0.0

name: ppocr-det

description: PP-OCRv3 Text Detection Model for book cover OCR

pipeline:
  - text_detection:
      model_name: ppocr_det
      input:
        type: image
        color_format: RGB
      preprocess:
        - resize:
            height: 640
            width: 640
        - torch-totensor:
            scale: false
        - normalize:
            mean: 127.5
            std: 127.5

models:
  ppocr_det:
    class: PPOCRv3DetModel
    class_path: $AXELERA_FRAMEWORK/ax_models/ocr/ppocr_det_model.py
    task_category: ObjectDetection
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 640, 640]
    input_color_format: RGB
    weight_path: $AXELERA_FRAMEWORK/../ocr-test/models/PP-OCRv3_det_fixed_640.onnx
    num_classes: 1
    dataset: TextDetDataset

datasets:
  TextDetDataset:
    class: DataAdapter
    labels_path: $AXELERA_FRAMEWORK/ax_datasets/labels/text_det.yaml
